import { GoogleGenAI, Type } from "@google/genai";
import supabase from "./supabase.js";


const CAMPUS_NAME = "DTU";
const PRIMARY_COLOR = "#990000";
const ML_API_URL = process.env.ML_API_URL || "/ML_analyze";

    /*
    TABLE SCHEMAS

    create table public.dispatchtickets (
      id smallint generated by default as identity not null,
      created_at timestamp with time zone not null default now(),
      issue text not null,
      category text null,
      "Risks" text null,
      "Image" text null,
      confidence real null,
      constraint dispatchtickets_pkey primary key (id),
      constraint dispatchtickets_id_key unique (id)
    ) TABLESPACE pg_default;

    create table public.tickets (
      id smallint generated by default as identity not null,
      created_at timestamp with time zone not null default now(),
      issue text not null,
      category text null,
      "Risks" text null,
      "Image" text null,
      confidence real null,
      is_dispatched boolean null,
      lat text null,
      long text null,
      constraint tickets_pkey primary key (id),
      constraint tickets_id_key unique (id)
    ) TABLESPACE pg_default;

    create table public."AuthorizedTime" (
      "TimeMin" time without time zone not null,
      "TimeMax" time without time zone null,
      "Name" text null
    ) TABLESPACE pg_default;
    */
const REPORT_SCHEMA = {
  type: Type.OBJECT,
  properties: {
    detectedIssue: { type: Type.STRING, description: "A short, single-line summary of the issue." },
    category: { type: Type.STRING },
    severityLevel: { type: Type.STRING },
    possibleRisks: { type: Type.STRING },
    confidenceLevel: { type: Type.NUMBER, description: "A value from 0 to 100 representing certainty." },
  },
  required: ["detectedIssue", "category", "severityLevel", "possibleRisks", "confidenceLevel"],
};

const ANALYSIS_PROMPT = `
You are a Senior Campus Infrastructure Inspector for ${CAMPUS_NAME}.
Your task is to analyze visual data and produce high-quality maintenance tickets.

CRITICAL INSTRUCTIONS ON SCORING:
1. CONFIDENCE LEVEL: This MUST be an integer between 0 and 100. 
   - If the issue is clearly identifiable, use 80-100. 
   - Low confidence should be below 60.
2. SEVERITY: 
   - 'High': Immediate danger or functional failure.
   - 'Medium': Functional issue that needs timely intervention.
   - 'Low': Cosmetic or non-urgent maintenance.
3. CATEGORY: (Maintenance, Cleanliness, Safety, Infrastructure, Electrical, Plumbing).
4. DETECTED ISSUE: Provide a short, single-line summary.

IMPORTANT:
- If the image looks normal or clean, report "No Issue" with a confidence of 0.
- Do not hallucinate issues.
- If sensor data is provided, verify it visually. If the image contradicts the sensor data, trust the image.

Respond ONLY with valid JSON. Focus on campus infrastructure.`;

let state = {
  currentView: 'DASHBOARD', 
  reports: [],
  dispatchedReports: [],
  stream: null,
  isAnalyzing: false,
  authorizedTimes: []
};

function getBrowserLocation() {
  return new Promise((resolve) => {
    if (!navigator.geolocation) {
      resolve(null);
      return;
    }
    navigator.geolocation.getCurrentPosition(
      (position) => {
        const { latitude, longitude } = position.coords;
        resolve({ lat: latitude, long: longitude });
      },
      (err) => {
        console.warn("Location retrieval failed", err);
        resolve(null);
      }
    );
  });
}

function haversineDistance(coords1, coords2) {
  if (!coords1 || !coords2 || !coords1.lat || !coords1.long || !coords2.lat || !coords2.long) return Infinity;
  const R = 6371; // Radius of the Earth in km
  const dLat = (coords2.lat - coords1.lat) * Math.PI / 180;
  const dLon = (coords2.long - coords1.long) * Math.PI / 180;
  const lat1 = coords1.lat * Math.PI / 180;
  const lat2 = coords2.lat * Math.PI / 180;

  const a = Math.sin(dLat / 2) * Math.sin(dLat / 2) +
            Math.sin(dLon / 2) * Math.sin(dLon / 2) * Math.cos(lat1) * Math.cos(lat2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return R * c; // Distance in km
}


async function analyzeImage(base64Data) {
  let mlContext = "";
  
  // 1. Attempt to consult the local ML Engine first
  try {
    // Convert Data URL to Blob for upload
    const fetchRes = await fetch(base64Data);
    const blob = await fetchRes.blob();
    const formData = new FormData();
    formData.append("file", blob, "image.jpg");

    // Check if current time is within any restricted AuthorizedTime range
    const now = new Date();
    const currentTime = now.toLocaleTimeString('en-US', { hour12: false, hour: '2-digit', minute: '2-digit', second: '2-digit' });
    const isRestricted = state.authorizedTimes.some(t => {
      return t.TimeMin && t.TimeMax && currentTime >= t.TimeMin && currentTime <= t.TimeMax;
    });

    if (isRestricted) {
      formData.append("check_unauthorized", "true");
    }

    // Call Python API (assuming default FastAPI port 8000)
    const mlResponse = await fetch(ML_API_URL, {
      method: "POST",
      body: formData
    });

    if (mlResponse.ok) {
      const mlResult = await mlResponse.json();
      // If the ML model found something, format it for Gemini
      if (mlResult) {
        mlContext = `\n\n[ADDITIONAL SENSOR DATA FROM COMPUTER VISION]:\n${JSON.stringify(mlResult)}\n\nNOTE: This sensor data may be a false positive. Only report issues that are clearly visible in the image.`;
        console.log("ML Engine Context:", mlResult);
      }
    }
  } catch (e) {
    console.warn("ML Engine unavailable, proceeding with visual analysis only.", e);
  }

  try {
    console.log("PRIMARY MODEL");
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    if (!ai) {
      console.log("API KEY ERROR");
    }
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: {
        parts: [
          { text: ANALYSIS_PROMPT + mlContext },
          {inlineData: { mimeType: "image/jpeg", data: base64Data.split(",")[1] || base64Data } }
        ]
      },
      config: {
        responseMimeType: "application/json",
        responseSchema: REPORT_SCHEMA,
      }
    });
    const jsonStr = response.text?.trim();
    if (!jsonStr) throw new Error("Empty response from primary model");
  
    const parsed = JSON.parse(jsonStr);
  
    if (parsed.confidenceLevel <= 1 && parsed.confidenceLevel > 0) {
      parsed.confidenceLevel = Math.round(parsed.confidenceLevel * 100);
    } else {
      parsed.confidenceLevel = Math.round(parsed.confidenceLevel || 0);
    }
    return parsed;
  } catch(err) {
    console.log("SECONDARY MODEL");
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    if (!ai) {
      console.log("API KEY ERROR");
    }
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: {
        parts: [
          { text: ANALYSIS_PROMPT + mlContext },
          { inlineData: { mimeType: "image/jpeg", data: base64Data.split(",")[1] || base64Data } }
        ]
      },
      config: {
        responseMimeType: "application/json",
        responseSchema: REPORT_SCHEMA,
      }
    });
    const jsonStr = response.text?.trim();
    if (!jsonStr) throw new Error("Empty response from secondary model");
  
    const parsed = JSON.parse(jsonStr);
  
    if (parsed.confidenceLevel <= 1 && parsed.confidenceLevel > 0) {
      parsed.confidenceLevel = Math.round(parsed.confidenceLevel * 100);
    } else {
      parsed.confidenceLevel = Math.round(parsed.confidenceLevel || 0);
    }
    return parsed;
  }
}


function getSeverityStyles(level) {
  switch(level) {
    case 'High': return { border: 'border-red-600', text: 'text-red-700', bg: 'bg-red-50', badge: 'bg-red-600 text-white', icon: 'fa-triangle-exclamation' };
    case 'Medium': return { border: 'border-orange-500', text: 'text-orange-700', bg: 'bg-orange-50', badge: 'bg-orange-500 text-white', icon: 'fa-circle-info' };
    case 'Low': return { border: 'border-blue-500', text: 'text-blue-700', bg: 'bg-blue-50', badge: 'bg-blue-500 text-white', icon: 'fa-clock' };
    default: return { border: 'border-gray-200', text: 'text-gray-500', bg: 'bg-gray-50', badge: 'bg-gray-500 text-white', icon: 'fa-circle-check' };
  }
}

function renderReportCard(report, isDispatched = false) {
  const styles = getSeverityStyles(report.severityLevel);
  const confidence = report.confidenceLevel || 0;
  
  return `
    <div class="bg-white rounded-3xl shadow-sm border border-gray-100 overflow-hidden animate-fade-in group hover:shadow-xl hover:shadow-gray-200/40 transition-all duration-500">
      <div class="md:flex h-full">
        ${report.imageUrl ? `
          <div class="md:w-[40%] h-64 md:h-auto relative overflow-hidden">
            <img src="${report.imageUrl}" class="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105" />
            <div class="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>
            <div class="absolute top-4 left-4 z-10">
               <span class="px-3 py-1.5 rounded-full shadow-lg text-[10px] font-black uppercase tracking-widest ${styles.badge} flex items-center">
                 <i class="fa-solid ${styles.icon} mr-2"></i> ${report.severityLevel} PRIORITY
               </span>
            </div>
          </div>
        ` : ''}
        <div class="p-8 md:w-[60%] flex flex-col justify-between">
          <div>
            <div class="flex items-start justify-between mb-6">
              <div>
                <h3 class="text-2xl font-black text-gray-900 leading-tight mb-2">${report.detectedIssue}</h3>
                <div class="flex items-center space-x-3">
                  <span class="text-[10px] font-bold text-[#990000] bg-red-50 px-2 py-1 rounded uppercase tracking-wider">${report.category}</span>
                  <span class="text-[10px] font-bold text-gray-400 uppercase tracking-widest flex items-center">
                    <i class="fa-solid fa-fingerprint mr-1.5"></i> AI Conf: ${confidence}%
                  </span>
                </div>
              </div>
            </div>

            <div class="grid grid-cols-2 gap-8 mb-8">
              <div>
                <p class="text-[9px] font-black text-gray-400 uppercase tracking-widest mb-2">Primary Unit</p>
                <p class="text-sm font-bold text-gray-800 flex items-center">
                  <span class="w-2.5 h-2.5 bg-gray-200 rounded-full mr-2.5"></span>
                  ${report.suggestedDepartment}
                </p>
              </div>
              <div>
                 <p class="text-[9px] font-black text-gray-400 uppercase tracking-widest mb-2">Safety Risks</p>
                 <p class="text-sm font-bold text-gray-800 truncate">${report.possibleRisks || 'Negligible'}</p>
              </div>
              <div class="col-span-2">
                 <p class="text-[9px] font-black text-gray-400 uppercase tracking-widest mb-2">Geotag Location</p>
                 <p class="text-sm font-bold text-gray-800 truncate flex items-center">
                   <i class="fa-solid fa-location-dot mr-2 text-red-700/50"></i>
                   ${report.location || 'Not Available'}
                 </p>
              </div>
            </div>

            <div class="${styles.bg} rounded-2xl p-5 mb-2 border border-white">
              <p class="text-[9px] font-black ${styles.text} uppercase tracking-widest mb-2">Inspector Diagnosis</p>
              <p class="text-sm text-gray-700 font-semibold leading-relaxed">${report.reasonForSeverity}</p>
            </div>
          </div>

          <div class="pt-6 mt-4 border-t border-gray-50 flex items-center justify-between">
             ${!isDispatched ? `
               <button onclick="window.discardTicket(${report.id})" class="text-[10px] font-black text-gray-400 hover:text-red-600 transition-all uppercase tracking-widest">
                 <i class="fa-solid fa-trash mr-1.5"></i> Discard
               </button>
               <button onclick="window.dispatchTicket(${report.id})" class="px-8 py-3.5 bg-[#990000] text-white rounded-2xl text-[11px] font-black shadow-xl shadow-red-900/10 hover:shadow-red-900/30 hover:scale-[1.02] active:scale-95 transition-all uppercase tracking-widest">
                 Dispatch Ticket
               </button>
             ` : `
               <div class="flex flex-col">
                  <span class="text-[9px] font-black text-gray-300 uppercase tracking-widest">Archived In System</span>
                  <span class="text-[10px] font-bold text-green-600 uppercase flex items-center">
                    <i class="fa-solid fa-check-double mr-1.5"></i> Transmission Complete
                  </span>
               </div>
               <button onclick="window.deleteDispatchedTicket(${report.id})" class="w-9 h-9 flex items-center justify-center rounded-xl bg-gray-50 text-gray-300 hover:text-red-400 transition-all">
                 <i class="fa-solid fa-xmark"></i>
               </button>
             `}
          </div>
        </div>
      </div>
    </div>
  `;
}

async function fetchAndSetTickets() {
  const { data, error } = await supabase
    .from('tickets')
    .select()
    .or('is_dispatched.is.null,is_dispatched.eq.false')
    .order('id', { ascending: false });

  if (error) {
    console.error("Could not fetch data from 'tickets' table:", error.message);
    return;
  }

  if (data) {
    let reports = data.map(ticket => ({
      id: ticket.id,
      detectedIssue: ticket.issue,
      category: ticket.category || 'Uncategorized',
      possibleRisks: ticket.Risks || 'Not specified',
      imageUrl: ticket.Image,
      location: ticket.lat && ticket.long ? `${ticket.lat}, ${ticket.long}` : 'Not Available',
      lat: ticket.lat,
      long: ticket.long,
      // Provide defaults for fields not in the database
      severityLevel: 'Medium',
      confidenceLevel: 0,
      reasonForSeverity: 'N/A',
      suggestedDepartment: 'Maintenance',
    })).sort((a, b) => b.id - a.id); 

    // Auto-dispatch logic for clustered tickets
    const ticketsWithLocation = reports.filter(t => t.lat && t.long);
    const processedTicketIds = new Set();
    const ticketsToDispatch = [];

    if (ticketsWithLocation.length > 2) {
      for (const ticket of ticketsWithLocation) {
        if (processedTicketIds.has(ticket.id)) {
          continue;
        }

        const nearbyGroup = ticketsWithLocation.filter(otherTicket => {
          const distance = haversineDistance(
            { lat: ticket.lat, long: ticket.long },
            { lat: otherTicket.lat, long: otherTicket.long }
          );
          return distance < 0.05; // 50 meters radius
        });

        if (nearbyGroup.length > 2) {
          nearbyGroup.forEach(t => {
            if (!processedTicketIds.has(t.id)) {
              ticketsToDispatch.push(t);
              processedTicketIds.add(t.id);
            }
          });
        }
      }
    }

    if (ticketsToDispatch.length > 0) {
      alert(`Found ${ticketsToDispatch.length} tickets in close proximity. Auto-dispatching now.`);
      
      // Set state.reports temporarily so dispatchTicket can find the tickets
      state.reports = reports;

      const dispatchPromises = ticketsToDispatch.map(t => window.dispatchTicket(t.id, false));
      await Promise.all(dispatchPromises);

      const dispatchedIds = new Set(ticketsToDispatch.map(t => t.id));
      reports = reports.filter(r => !dispatchedIds.has(r.id));
    }

    state.reports = reports;
    updateUI();
  }
}

async function fetchAndSetDispatchedTickets() {
  const { data, error } = await supabase.from('dispatchtickets').select().order('id', { ascending: false });

  if (error) {
    console.error("Could not fetch data from 'dispatchtickets' table:", error.message);
    state.dispatchedReports = [];
  } else if (data) {
    state.dispatchedReports = data.map(ticket => ({
      id: ticket.id,
      detectedIssue: ticket.issue,
      category: ticket.category || 'Uncategorized',
      possibleRisks: ticket.Risks || 'Not specified',
      imageUrl: ticket.Image,
      location: ticket.lat && ticket.long ? `${ticket.lat}, ${ticket.long}` : 'Not Available',
      // Provide defaults for the card to render
      severityLevel: 'Dispatched',
      confidenceLevel: 100,
      reasonForSeverity: 'This ticket has been dispatched and is archived.',
      suggestedDepartment: 'Maintenance',
    }));
  }
}

async function fetchAuthorizedTimes() {
  const { data, error } = await supabase.from('AuthorizedTime').select('*');
  if (error) {
    console.error("Could not fetch AuthorizedTime:", error.message);
  } else if (data) {
    state.authorizedTimes = data;
  }
}


async function updateUI() {
  const activeViews = ['DASHBOARD', 'LIVE', 'UPLOAD'];
  activeViews.forEach(v => {

    const el = document.getElementById(`nav-${v}`);
    if (el) {
      if (state.currentView === v) el.classList.add('active-nav');
      else el.classList.remove('active-nav');
    }
    // Desktop Nav
    const btn = document.getElementById(`nav-btn-${v}`);
    if (btn) {
      if (state.currentView === v) {
        btn.classList.add('active-nav');
        btn.classList.remove('text-gray-400', 'hover:text-gray-900', 'hover:bg-gray-50');
      } else {
        btn.classList.remove('active-nav');
        btn.classList.add('text-gray-400', 'hover:text-gray-900', 'hover:bg-gray-50');
      }
    }
  });

  document.querySelectorAll('.view-section').forEach(el => el.classList.add('hidden'));
  
  const desktopNav = document.getElementById('desktop-nav');
  if (state.currentView === 'ADMIN') desktopNav.classList.add('hidden');
  else desktopNav.classList.remove('hidden');

  if (state.currentView === 'DASHBOARD') {
    document.getElementById('view-dashboard').classList.remove('hidden');
    updateDashboardData();
  } else if (state.currentView === 'LIVE') {
    document.getElementById('view-live').classList.remove('hidden');
    await setupLiveView();
  } else if (state.currentView === 'UPLOAD') {
    document.getElementById('view-upload').classList.remove('hidden');
    // Upload view is static, no data update needed on switch
  } else if (state.currentView === 'ADMIN') {
    document.getElementById('view-admin').classList.remove('hidden');
    await updateAdminData();
  }
}

function updateDashboardData() {
  const activeCount = state.reports.length;
  const highPriority = state.reports.filter(r => r.severityLevel === 'High').length;
  
  document.getElementById('dash-queue-count').textContent = activeCount;
  const highCountEl = document.getElementById('dash-high-count');
  highCountEl.textContent = highPriority;
  highCountEl.className = `text-5xl font-black ${highPriority > 0 ? 'text-red-600' : 'text-gray-900'}`;
  
  const percentage = activeCount > 0 ? (highPriority/activeCount)*100 : 0;
  document.getElementById('dash-severity-bar').style.width = `${percentage}%`;
  
  document.getElementById('dash-total-badge').textContent = `${activeCount} Reports`;
  
  const container = document.getElementById('dash-reports-container');
  if (state.reports.length === 0) {
    container.innerHTML = `
      <div class="flex flex-col items-center justify-center py-28 bg-white rounded-[3rem] border-4 border-dashed border-gray-50 text-center">
        <div class="w-24 h-24 bg-gray-50 rounded-full flex items-center justify-center mb-6">
          <i class="fa-solid fa-shield-cat text-gray-100 text-4xl"></i>
        </div>
        <h3 class="text-xl font-black text-gray-900 mb-2 uppercase tracking-tighter">Zero Alerts Detected</h3>
        <p class="text-gray-400 font-medium text-sm max-w-xs leading-relaxed">System is running in idle mode. Use the camera or upload tools to begin campus inspection.</p>
      </div>`;
  } else {
    container.innerHTML = state.reports.map(r => renderReportCard(r)).join('');
  }
}

async function updateAdminData() {
  await fetchAndSetDispatchedTickets();

  document.getElementById('admin-dispatched-count').textContent = state.dispatchedReports.length;
  
  const container = document.getElementById('admin-reports-container');
  if (state.dispatchedReports.length === 0) {
    container.innerHTML = `
      <div class="flex flex-col items-center justify-center py-32 bg-white rounded-[3rem] border border-gray-100 shadow-sm text-center">
        <div class="w-24 h-24 bg-gray-50 rounded-full flex items-center justify-center mb-6">
          <i class="fa-solid fa-folder-tree text-gray-100 text-4xl"></i>
        </div>
        <h3 class="text-xl font-black text-gray-900 uppercase tracking-tighter mb-2">Registry Empty</h3>
        <p class="text-gray-400 text-sm font-medium">Tickets will be archived here once they are dispatched to maintenance.</p>
      </div>`;
  } else {
    container.innerHTML = state.dispatchedReports.map(report => renderReportCard(report, true)).join('');
  }
}

async function setupLiveView() {
  const video = document.getElementById('monitor-video');
  
  try {
    state.stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'environment' } });
    video.srcObject = state.stream;
  } catch (err) { alert("Camera access denied. Please ensure you have given permissions."); }
}

// --- Global Handlers ---
window.setView = (view) => {
  if (state.stream) {
    state.stream.getTracks().forEach(track => track.stop());
    state.stream = null;
  }
  state.currentView = view;
  updateUI();
};

window.discardTicket = async (id) => {
  if(confirm("Permanently discard this diagnostic session?")) {
    const { error } = await supabase
      .from('tickets')
      .delete()
      .eq('id', id);

    if (error) {
      alert(`Failed to delete ticket: ${error.message}`);
      return;
    }

    state.reports = state.reports.filter(r => r.id !== id);
    updateUI();
  }
};

window.dispatchTicket = async (id, showAlertAndUpdateUI = true) => {
  const reportToDispatch = state.reports.find(r => r.id === id);
  if (!reportToDispatch) {
    console.error("Could not find report to dispatch in local state.");
    return;
  }

  // 1. Insert into dispatchtickets table
  const { data: newDispatchedTicket, error: insertError } = await supabase
    .from('dispatchtickets')
    .insert({
      issue: reportToDispatch.detectedIssue,
      category: reportToDispatch.category,
      Risks: reportToDispatch.possibleRisks,
      Image: reportToDispatch.imageUrl,
      lat: reportToDispatch.lat,
      long: reportToDispatch.long,
    }).select().single();

  if (insertError) {
    const errorMessage = `Failed to create record in dispatched tickets: ${insertError.message}`;
    if (showAlertAndUpdateUI) {
      alert(errorMessage);
    } else {
      console.error(`${errorMessage} for ticket id ${id}`);
    }
    return;
  }

  // 2. Delete from the original tickets table
  const { error: deleteError } = await supabase
    .from('tickets')
    .delete()
    .eq('id', id);

  if (deleteError) {
    const errorMessage = `Failed to delete original ticket: ${deleteError.message}. Rolling back.`;
    if (showAlertAndUpdateUI) {
      alert(errorMessage);
    } else {
      console.error(`${errorMessage} for ticket id ${id}`);
    }
    // Rollback the insertion
    await supabase.from('dispatchtickets').delete().eq('id', newDispatchedTicket.id);
    return;
  }

  // 3. Update local state and UI
  if (showAlertAndUpdateUI) {
    state.reports = state.reports.filter(r => r.id !== id);
    alert(`TRANSMITTED: Resource dispatched to ${reportToDispatch.suggestedDepartment}.`);
    updateUI();
  }
};

window.deleteDispatchedTicket = async (id) => {
  if(confirm("Purge this archived record?")) {
    const { error } = await supabase.from('dispatchtickets').delete().eq('id', id);
    if (error) alert(`Failed to purge record: ${error.message}`);
    updateUI();
  }
};

document.getElementById('capture-btn').addEventListener('click', async () => {
  if (state.isAnalyzing) return;
  
  const video = document.getElementById('monitor-video');
  const resultContainer = document.getElementById('live-result-container');
  const statusContainer = document.getElementById('analysis-status');
  const captureContainer = document.getElementById('capture-container');

  // Redesigned loading state
  state.isAnalyzing = true;
  statusContainer.innerHTML = `<div class="text-center p-4"><i class="fa-solid fa-spinner-third fa-spin text-2xl text-[#990000]"></i><p class="text-xs font-bold mt-2 uppercase">Analyzing...</p></div>`;
  statusContainer.classList.remove('hidden');
  captureContainer.classList.add('hidden');
  resultContainer.innerHTML = '';

  const canvas = document.createElement('canvas');
  canvas.width = video.videoWidth;
  canvas.height = video.videoHeight;
  canvas.getContext('2d').drawImage(video, 0, 0);
  const dataUrl = canvas.toDataURL('image/jpeg');
  
  try {
    const locationPromise = getBrowserLocation();
    const result = await analyzeImage(dataUrl);
    const locationObj = await locationPromise;

    const { data: newTicket, error } = await supabase
      .from('tickets')
      .insert({
        issue: result.detectedIssue,
        category: result.category,
        Risks: result.possibleRisks,
        Image: dataUrl,
        is_dispatched: false,
        lat: locationObj?.lat,
        long: locationObj?.long,
      })
      .select()
      .single();

    if (error) {
      throw new Error(`Supabase Error: ${error.message}`);
    }

    const report = {
      id: newTicket.id,
      detectedIssue: newTicket.issue,
      category: newTicket.category,
      possibleRisks: newTicket.Risks,
      imageUrl: newTicket.Image,
      location: locationObj ? `${locationObj.lat}, ${locationObj.long}` : 'Not Available',
      lat: locationObj?.lat,
      long: locationObj?.long,
      severityLevel: result.severityLevel,
      confidenceLevel: result.confidenceLevel,
      reasonForSeverity: 'AI-generated based on visual analysis.',
      suggestedDepartment: 'Maintenance'
    };
    
    state.reports.unshift(report);
    resultContainer.innerHTML = `
      <div class="mt-8">
         <div class="flex items-center space-x-2 mb-6">
           <div class="h-px bg-gray-200 flex-1"></div>
           <span class="text-[10px] font-black text-gray-400 uppercase tracking-widest">Diagnostic Report Generated</span>
           <div class="h-px bg-gray-200 flex-1"></div>
         </div>
         ${renderReportCard(report)}
      </div>
    `;
  } catch (err) {
    console.error(err);
    resultContainer.innerHTML = `<div class="text-center p-8 bg-red-50 text-red-700 rounded-2xl mt-8"><strong>Analysis Failed:</strong> ${err.message}</div>`;
  } finally {
    state.isAnalyzing = false;
    statusContainer.classList.add('hidden');
    captureContainer.classList.remove('hidden');
  }
});

document.getElementById('file-input').addEventListener('change', (e) => {
  const file = e.target.files[0];
  if (!file) return;

  const reader = new FileReader();
  reader.onload = async (event) => {
    const dataUrl = event.target.result;
    const resultContainer = document.getElementById('upload-result-container');
    const statusContainer = document.getElementById('upload-status');
    const uploadArea = document.getElementById('upload-area');

    statusContainer.innerHTML = `<div class="text-center p-4"><i class="fa-solid fa-spinner-third fa-spin text-2xl text-[#990000]"></i><p class="text-xs font-bold mt-2 uppercase">Analyzing...</p></div>`;
    statusContainer.classList.remove('hidden');
    resultContainer.innerHTML = '';
    if(uploadArea) uploadArea.style.display = 'none';

    try {
      const locationPromise = getBrowserLocation();
      const result = await analyzeImage(dataUrl);
      const locationObj = await locationPromise;

      const { data: newTicket, error } = await supabase
        .from('tickets')
        .insert({
          issue: result.detectedIssue,
          category: result.category,
          Risks: result.possibleRisks,
          Image: dataUrl,
        is_dispatched: false,
        lat: locationObj?.lat,
        long: locationObj?.long,
        })
        .select()
        .single();

      if (error) {
        throw new Error(`Supabase Error: ${error.message}`);
      }

      const report = {
        id: newTicket.id,
        detectedIssue: newTicket.issue,
        category: newTicket.category,
        possibleRisks: newTicket.Risks,
        imageUrl: newTicket.Image,
        location: locationObj ? `${locationObj.lat}, ${locationObj.long}` : 'Not Available',
        lat: locationObj?.lat,
        long: locationObj?.long,
        severityLevel: result.severityLevel,
        confidenceLevel: result.confidenceLevel,
        reasonForSeverity: 'AI-generated based on visual analysis.',
        suggestedDepartment: 'Maintenance'
      };

      state.reports.unshift(report);
      resultContainer.innerHTML = `
        <div class="mt-8">
          <div class="h-px bg-gray-200 w-full mb-8"></div>
          ${renderReportCard(report)}
        </div>
      `;
    } catch (err) {
      console.error(err);
      resultContainer.innerHTML = `<div class="text-center p-8 bg-red-50 text-red-700 rounded-2xl mt-8"><strong>Analysis Failed:</strong> ${err.message}</div>`;
    } finally {
      statusContainer.classList.add('hidden');
      if(uploadArea) uploadArea.style.display = 'flex';
      e.target.value = '';
    }
  };
  reader.readAsDataURL(file);
});

// 2. Start App
fetchAndSetTickets();
fetchAuthorizedTimes();
updateUI();